### ISSUE TITLE
Why exchange to PLN

### ISSUE THREAD

**Issue by ovresko** [zonkia/XTB-autoTrader#1]
Hi, first i want to congratulates you for this work, i'm wan't to contribute but there's some thing i can't understand,
like the fact you request exchange value for PLN currency currencyExchangePLN, why ?
 
self.positionLots[pair] = truncate(equity / currencyExchangePLN[pair] /
                                                           100000 * riskRate /
                                                           (self.positionSL[pair] / bidAsk.askPrices[pair] -
                                                            1) * (-1), 2)

**Comment by zonkia** [comment]
Hi, thanks. This currencyExchangePLN is necessary because the basic account is in PLN. So if you trade EURUSD and you have your account in PLN, you need to know the EURPLN exchange rate to calculate the position size, stop loss size etc.

In this example that you sent, the position size is calculated

Wysłane z iPhone'a
